Repository micronaut-projects/micronaut-maven-plugin, pull requests merged in 2023-09, with the labels that each got.

#835 Upgrade to Micronaut AOT 2.1.0
  micronaut-maven-integration-tests/src/it/issue465/aot-jar.properties
  micronaut-maven-integration-tests/src/it/issue582/aot-jar.properties
  micronaut-maven-integration-tests/src/it/issue582/aot-native-image.properties
  micronaut-maven-integration-tests/src/it/run-aot/expected-effective-aot.properties
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/aot/Constants.java
  pom.xml
Labels: type: dependency-upgrade

#843 Fix CRaC JDK download in docker container
  src/it/dockerfile-docker-crac/Dockerfile.crac.checkpoint
  src/main/resources/dockerfiles/DockerfileCracCheckpoint
Labels: type: bug

#847 Use an Arm compatible base image for docker-native on arm
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/Dockerfile
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/invoker.properties
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/pom.xml
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/src/main/java/io/micronaut/build/examples/Application.java
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/src/main/resources/application.yml
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/src/main/resources/logback.xml
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/src/test/java/io/micronaut/build/examples/ApplicationTest.java
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-arm/verify.groovy
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/Dockerfile
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/invoker.properties
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/pom.xml
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/src/main/java/io/micronaut/build/examples/Application.java
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/src/main/resources/application.yml
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/src/main/resources/logback.xml
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/src/test/java/io/micronaut/build/examples/ApplicationTest.java
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-base/verify.groovy
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/Dockerfile.aarch64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/Dockerfile.amd64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/verify.groovy
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty/Dockerfile.aarch64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty/Dockerfile.amd64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty/verify.groovy
  micronaut-maven-integration-tests/src/it/package-docker-crac/selector.groovy
  micronaut-maven-integration-tests/src/it/package-docker-native/verify.groovy
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/AbstractDockerMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerNativeMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerfileMojo.java
Labels: relates-to: graal
