Repository micronaut-projects/micronaut-maven-plugin, pull requests merged in 2023-06, with the labels that each got.

#753 Upgrade to Test Resources M10
  micronaut-maven-integration-tests/pom.xml
  micronaut-maven-integration-tests/src/it/run-aot/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-custom-dependency/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-failing-test/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-shared-namespace/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-shared/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-start-stop/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources/pom.xml
  micronaut-maven-plugin/pom.xml
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/DefaultServerFactory.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesLifecycleExtension.java
  pom.xml
Labels: type: improvement

#747 Initial implementation of OpenAPI generation
  micronaut-maven-integration-tests/src/it/openapi-generate-client/invoker.properties
  micronaut-maven-integration-tests/src/it/openapi-generate-client/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-client/src/main/java/io/micronaut/build/examples/Application.java
  micronaut-maven-integration-tests/src/it/openapi-generate-client/src/main/java/io/micronaut/build/examples/greeter/Greeter.java
  micronaut-maven-integration-tests/src/it/openapi-generate-client/src/main/resources/application.yml
  micronaut-maven-integration-tests/src/it/openapi-generate-client/src/main/resources/logback.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-client/src/openapi/petstore.json
  micronaut-maven-integration-tests/src/it/openapi-generate-client/src/test/java/io/micronaut/build/examples/ApplicationTest.java
  micronaut-maven-integration-tests/src/it/openapi-generate-client/verify.groovy
  micronaut-maven-integration-tests/src/it/openapi-generate-server/invoker.properties
  micronaut-maven-integration-tests/src/it/openapi-generate-server/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-server/src/main/resources/application.yml
  micronaut-maven-integration-tests/src/it/openapi-generate-server/src/main/resources/logback.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-server/src/openapi/petstore.json
  micronaut-maven-integration-tests/src/it/openapi-generate-server/src/test/java/io/micronaut/build/examples/ApplicationTest.java
  micronaut-maven-integration-tests/src/it/openapi-generate-server/verify.groovy
  micronaut-maven-plugin/pom.xml
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/AbstractOpenApiMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/OpenApiClientMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/OpenApiServerMojo.java
  micronaut-maven-plugin/src/main/resources/META-INF/plexus/components.xml
  micronaut-maven-plugin/src/site/asciidoc/examples/openapi.adoc
  micronaut-maven-plugin/src/site/asciidoc/index.adoc
  micronaut-maven-plugin/src/site/site.xml
  pom.xml
Labels: type: enhancement

#772 Pass Test Resources system properties when running from mn:run
  micronaut-maven-integration-tests/src/it/test-resources-run/invoker.properties
  micronaut-maven-integration-tests/src/it/test-resources-run/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/Application.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/Book.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/BookController.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/BookRepository.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/User.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/UserController.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/java/io/micronaut/build/examples/UserRepository.java
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/resources/application.yml
  micronaut-maven-integration-tests/src/it/test-resources-run/src/main/resources/logback.xml
  micronaut-maven-integration-tests/src/it/test-resources-run/src/test/java/io/micronaut/build/examples/DemoTest.java
  micronaut-maven-integration-tests/src/it/test-resources-run/verify.groovy
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/services/DependencyResolutionService.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
Labels: type: bug
