Repository micronaut-projects/micronaut-maven-plugin, pull requests merged in 2023-07, with the labels that each got.

#773 Update to GraalVM for JDK 17 (fka GraalVM 23.0)
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-distroless/Dockerfile
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty-custom-ol/Dockerfile
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-netty/Dockerfile
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-oracle-function/Dockerfile
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-static/Dockerfile
  micronaut-maven-integration-tests/src/it/package-docker-native-static/Dockerfile
  micronaut-maven-integration-tests/src/it/package-docker-native-static/selector.groovy
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/AbstractDockerMojo.java
  micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
  micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileNativeStatic
  micronaut-maven-plugin/src/site/asciidoc/examples/package.adoc
Labels: type: dependency-upgrade

#774 Add support for openapi mappings
  micronaut-maven-integration-tests/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-client/verify.groovy
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/invoker.properties
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/src/main/java/io/micronaut/openapi/controller/MappedController.java
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/src/main/java/io/micronaut/openapi/dated/DatedResponse.java
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/src/main/java/io/micronaut/openapi/filter/MyFilter.java
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/src/openapi/spec.yaml
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/verify.groovy
  micronaut-maven-integration-tests/src/it/openapi-generate-server/verify.groovy
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/invoker.properties
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/src/main/resources/application.yml
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/src/main/resources/logback.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/src/openapi/petstore.json
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/src/test/java/io/micronaut/build/examples/ApplicationTest.java
  micronaut-maven-integration-tests/src/it/openapi-generate-sources/verify.groovy
  micronaut-maven-integration-tests/src/it/openapi-setup/invoker.properties
  micronaut-maven-integration-tests/src/it/openapi-setup/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-setup/src/main/java/io/micronaut/maven/fixtures/DummyOpenApiGenerator.java
  micronaut-maven-integration-tests/src/it/openapi-setup/src/main/java/io/micronaut/maven/fixtures/DummyOptionsBuilder.java
  micronaut-maven-integration-tests/src/it/openapi-setup/src/main/resources/templates/java-micronaut/server/dummy.mustache
  micronaut-maven-integration-tests/src/it/openapi-setup/verify.groovy
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/AbstractOpenApiMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/OpenApiClientMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/OpenApiGenericMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/OpenApiServerMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/ParameterMapping.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/ResponseBodyMapping.java
  micronaut-maven-plugin/src/main/resources/META-INF/plexus/components.xml
  pom.xml
Labels: type: improvement

#779 Bump Test Resources and AOT to their latest versions
  pom.xml
Labels: type: dependency-upgrade

#780 Correctly resolve source directories
  examples/groovy/pom.xml
  examples/groovy/src/main/groovy/io/micronaut/maven/examples/Application.groovy
  examples/groovy/src/main/resources/application.properties
  examples/groovy/src/main/resources/logback.xml
  examples/groovy/src/test/groovy/com/example/DemoTest.groovy
  examples/java/.gitignore
  examples/java/Dockerfile.example
  examples/java/micronaut-cli.yml
  examples/java/mvnw
  examples/java/mvnw.cmd
  examples/java/pom.xml
  examples/kotlin/pom.xml
  examples/kotlin/src/main/kotlin/io/micronaut/maven/examples/Application.kt
  examples/kotlin/src/main/resources/application.properties
  examples/kotlin/src/main/resources/logback.xml
  examples/kotlin/src/test/kotlin/com/example/DemoKotlinTest.kt
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/services/CompilerService.java
Labels: type: bug

#786 Test Resources GA
  pom.xml
Labels: type: dependency-upgrade

#793 update micronaut-parent coordinates
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/DockerNativeMojo.java
Labels: type: bug

#799 Rollback to Amazon Linux 2
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.aarch64
  micronaut-maven-integration-tests/src/it/dockerfile-docker-native-lambda/Dockerfile.amd64
  micronaut-maven-plugin/src/main/resources/dockerfiles/DockerfileAwsCustomRuntime
  micronaut-maven-plugin/src/site/asciidoc/examples/package.adoc
Labels: type: bug
