Repository micronaut-projects/micronaut-maven-plugin, pull requests merged in 2024-10, with the labels that each got.

#1192 build: set version to 4.7.0-SNAPSHOT
  micronaut-maven-core/pom.xml
  micronaut-maven-enforcer-rules/pom.xml
  micronaut-maven-integration-tests/pom.xml
  micronaut-maven-jib-integration/pom.xml
  micronaut-maven-plugin/pom.xml
  pom.xml
Labels: relates-to: build

#1190 Upgrade Test Resources
  micronaut-maven-integration-tests/pom.xml
  micronaut-maven-integration-tests/src/it/openapi-generate-server-mapped-types/src/main/java/io/micronaut/openapi/controller/MappedController.java
  micronaut-maven-integration-tests/src/it/package-docker-down/pom.xml
  micronaut-maven-integration-tests/src/it/test-resources-start-stop/verify.groovy
  micronaut-maven-jib-integration/pom.xml
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
  pom.xml
Labels: type: bug

#1224 Fix site generation
  micronaut-maven-plugin/src/site/asciidoc/usage.adoc
  micronaut-maven-plugin/src/site/site.xml
  pom.xml
Labels: type: docs

#1236 Allow running Test Resources as a non-daemon process
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/DefaultServerFactory.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/StartTestResourcesServerMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/StopTestResourcesServerMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesConfiguration.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
Labels: type: improvement
