Repository micronaut-projects/micronaut-maven-plugin, pull requests merged in 2025-01, with the labels that each got.

#1267 This fixes #1266
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/aot/AbstractMicronautAotCliMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/aot/AotAnalysisMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/aot/AotSampleMojo.java
Labels: type: bug

#1257 Fixed default value for `micronaut.openapi.generate.http.response.where.required`
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/openapi/AbstractOpenApiMojo.java
Labels: type: bug

#1289 Support passing system properties to the Test Resources service
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/RunMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/AbstractTestResourcesMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/DefaultServerFactory.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/StartTestResourcesServerMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/StopTestResourcesServerMojo.java
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/testresources/TestResourcesHelper.java
  micronaut-maven-plugin/src/test/java/io/micronaut/maven/testresources/DefaultServerFactoryTest.java
Labels: type: improvement

#1290 JsonSchema Generator plugin in maven
  micronaut-maven-integration-tests/src/it/jsonschema-generate/invoker.properties
  micronaut-maven-integration-tests/src/it/jsonschema-generate/pom.xml
  micronaut-maven-integration-tests/src/it/jsonschema-generate/src/main/resources/animal.schema.json
  micronaut-maven-integration-tests/src/it/jsonschema-generate/verify.groovy
  micronaut-maven-plugin/pom.xml
  micronaut-maven-plugin/src/main/java/io/micronaut/maven/jsonschema/JsonSchemaGeneratorMojo.java
  micronaut-maven-plugin/src/main/resources/META-INF/plexus/components.xml
  micronaut-maven-plugin/src/site/asciidoc/examples/jsonschema.adoc
  micronaut-maven-plugin/src/site/asciidoc/index.adoc
  micronaut-maven-plugin/src/site/site.xml
  pom.xml
Labels: type: enhancement
